// <auto-generated />
namespace MvcLocalizationDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedResourceEntry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedResourceEntry));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151949024_AddedResourceEntry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
